// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGpA6qZo_AQ7qDxdkXQvr1_BfgY6Sxso',
    appId: '1:789085772151:web:f9c3ac99a51092b48c6972',
    messagingSenderId: '789085772151',
    projectId: 'store-48',
    authDomain: 'store-48.firebaseapp.com',
    storageBucket: 'store-48.appspot.com',
    measurementId: 'G-MYGWJPJVZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCLxgqx_YDHlXtlAbNfb-2WXUjEV9TDo4',
    appId: '1:789085772151:android:25a688c64058baa48c6972',
    messagingSenderId: '789085772151',
    projectId: 'store-48',
    storageBucket: 'store-48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzY_r-U2OE6W13_-WkcRbH6_wk70ypug',
    appId: '1:789085772151:ios:5163b0ba75b502a18c6972',
    messagingSenderId: '789085772151',
    projectId: 'store-48',
    storageBucket: 'store-48.appspot.com',
    iosClientId: '789085772151-lrrmhodri565bka18dah5dsk30q51543.apps.googleusercontent.com',
    iosBundleId: 'com.example.store48',
  );
}
